version: '3.8'

services:
  # Serviço Nginx (Servidor Web)
  nginx:
    image: nginx:1.25-alpine
    container_name: receitas_apocalipticas_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - receitas_network
    restart: unless-stopped
  # Serviço PHP-FPM
  php:
    build: .
    container_name: receitas_apocalipticas_php
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=receitas_apocalipticas
      - DB_USER=receitas_user
      - DB_PASS=receitas123
    networks:
      - receitas_network
    restart: unless-stopped

  # Serviço MySQL
  db:
    image: mysql:8.0
    container_name: receitas_apocalipticas_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: receitas123
      MYSQL_DATABASE: receitas_apocalipticas
      MYSQL_USER: receitas_user
      MYSQL_PASSWORD: receitas123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_setup.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/mysql-config.cnf
    networks:
      - receitas_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Serviço phpMyAdmin (opcional, para gerenciamento do banco)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: receitas_apocalipticas_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: receitas123
      MYSQL_ROOT_PASSWORD: receitas123
    depends_on:
      - db
    networks:
      - receitas_network
    restart: unless-stopped

# Volumes para persistência de dados
volumes:
  mysql_data:
    driver: local

# Rede personalizada
networks:
  receitas_network:
    driver: bridge
